version: "3.7"
services:
  prometheus:
    image: linuxtips/prometheus_alpine
    volumes:
      - ./conf/prometheus/:/etc/prometheus
      - prometheus_data:/var/lib/prometheus
    ports: 
      - 9090:9090
  node-exporter:
    image: linuxtips/node-exporter_alpine
    hostname: '{{.Node.ID}}'
    volumes:
    - /proc:/usr/proc
    - /sys:/usr/sys
    - /:/rootfs
    networks:
    - backend
    deploy:
      mode:
        global
    ports:
      -9100:9100
  alertmanager:
    image: linuxtips/alertmanager_alpine
    volumes:
    - ./conf/alertmanager/:/etc/alertmanager;
    ports: 
    - 9093:9093
    networks:
    - backend
    depends_on:
    - redis
  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - ./conf/alertmanager/:/etc/alertmanager/
    ports:
    - 9093:9093
    networks:
    - backend
  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - 8080:8080
    networks:
    - backend
  grafana:
    image: nopp/grafana_alpine
    depends_on:
      - prometheus
    networks:
    - frontend
    - backend
    ports:
      -3000:3000
networks:
  frontend:
  backend:
volumes:
  prometheus_data:
